### ISSUE TITLE
about mongodb error

### ISSUE THREAD

**Issue by edenli95** [chengjoey/django_celery#7]
你好，作者，我有个问题能方便解答一下吗， @chengjoey 

当我正常运行了MongoDB服务，mongod.exe dbpath='d:\data\db'，可以登录127.0.0.1/27017，显示“It looks like you are trying to access MongoDB over HTTP on the native driver port.”
然后先运行python3 manage.py runserver（3389端口我这边被系统占用了，用了默认8000），再运行celery worker -A mysite -l info出现错误，
[2021-05-13 10:20:42,278: ERROR/MainProcess] consumer: Cannot connect to mongodb://mongodb:27017/celery_jobs: mongodb:27017: [Errno 11001] getaddrinfo failed.
Trying again in 2.00 seconds...
你知道可能是什么情况吗

**Comment by chengjoey** [comment]
> access MongoDB over HTTP on the native driver port

报错貌似是因为mongodb的原因哦,我没遇到过,在[https://stackoverflow.com/questions/23446876/cannot-access-mongodb-through-browser-it-looks-like-you-are-trying-to-access-m](stack)上似乎有类似的问题,你看看能不能解决
